language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - stable
script:
  - yarn build
  - yarn test
deploy:
  provider: netlify
  site: modest-nobel-e11ae1
  edge: true
